name: speed_up
description: Package to speed up your productivity.
version: 0.6.9
homepage: https://github.com/AndrewPiterov/speed_up

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fluent_result: ^4.3.0
  meta: ^1.7.0
  quiver: ^3.0.1+1

dev_dependencies:
  equatable: ^2.0.3
  given_when_then_unit_test: ^0.0.9
  lint: ^1.8.2
  shouldly: ^0.4.0+1
  test: ^1.20.1