name: speed_up
description: Package to speed up your productivity.
version: 0.2.1
homepage: https://github.com/AndrewPiterov/speed_up

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.16.8
