name: speed_up
description: Package to speed up your productivity.
version: 0.9.0
homepage: https://github.com/AndrewPiterov/speed_up

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  meta: ^1.9.1
  quiver: ^3.2.1

dev_dependencies:
  given_when_then_unit_test: ^0.2.1
  lint: ^2.3.0
  shouldly: ^0.5.0+1
  test: ^1.24.3