name: speed_up
description: Package to speed up your productivity.
version: 0.8.1
homepage: https://github.com/AndrewPiterov/speed_up

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fluent_result: ^5.0.0
  meta: ^1.7.0
  quiver: ^3.1.0

dev_dependencies:
  equatable: ^2.0.3
  given_when_then_unit_test: ^0.1.0
  lint: ^1.8.2
  shouldly: ^0.5.0+1
  test: ^1.20.1