name: speed_up
description: Package to speed up your productivity.
version: 0.4.2
homepage: https://github.com/AndrewPiterov/speed_up

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fluent_result: ^4.0.1

dev_dependencies:
  test: ^1.17.12
  shouldly: ^0.1.3