name: speed_up
description: Package to speed up your productivity.
version: 0.0.1
author: AndrewPiterov.pro
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.16.8
